export const inputTypes = [
    "button",
    "checkbox",
    "color",
    "date",
    "datetime-local",
    "email",
    "file",
    "hidden",
    "image",
    "month",
    "number",
    "password",
    "radio",
    "range",
    "reset",
    "search",
    "submit",
    "tel",
    "text",
    "time",
    "url",
    "week",
];

export const inputCategories = {
    writeable: ['text', 'number', 'url', 'email', 'search', 'tel'],
    password: ['password'],
    date: ['date', 'datetime-local', 'month', 'time', 'week'],
    buttons: ['button', 'submit', 'reset'],
    selectable: ['radio', 'checkbox'],
    hiddenField: ['hidden'],
    colorPicker: ['color'],
    image: ['image'],
    sliders: ['range'],
    upload: ['file'],
}


export const inputTypesWithArguments = {
    text: ["maxlength", "placeholder", "required", "readonly", "autofocus", "pattern"],
    number: ["min", "max", "step", "placeholder", "required", "readonly", "autofocus"],
    password: ["maxlength", "placeholder", "required", "readonly", "autofocus", "pattern"],
    email: ["maxlength", "placeholder", "required", "readonly", "autofocus", "pattern"],
    tel: ["maxlength", "placeholder", "required", "readonly", "autofocus", "pattern"],
    date: ["min", "max", "placeholder", "required", "readonly", "autofocus"],
    time: ["min", "max", "placeholder", "required", "readonly", "autofocus"],
    checkbox: ["checked", "required"],
    radio: ["checked", "required"],
    range: ["min", "max", "step", "value"],
    file: ["accept", "multiple", "required"],
    color: ["value", "required", "readonly", "autofocus"],
    submit: ["value", "formaction", "formmethod", "formenctype", "formtarget"],
    button: ["value"],
    reset: ["value"],
    search: ["maxlength", "placeholder", "required", "readonly", "autofocus"],
    image: ["src", "alt", "width", "height"],
    url: ["maxlength", "placeholder", "required", "readonly", "autofocus", "pattern"],
    month: ["min", "max", "placeholder", "required", "readonly", "autofocus"],
    week: ["min", "max", "placeholder", "required", "readonly", "autofocus"],
    datetime: ["min", "max", "placeholder", "required", "readonly", "autofocus"],
    datetimeLocal: ["min", "max", "placeholder", "required", "readonly", "autofocus"],
    hidden: ["value"],
};